### PR TITLE
remove useless junk

### PR DESCRIPTION
**Pull request by ZVL2SOQEE4**
you can use fanciful by @mkremins directly and actually you can just delete "project scorpion"

### CODE REVIEW

**Comment by Jaryn-R** [comment]
1. We will not be remove Projekt-Scorpio because I have a later use for the library, it's not only going to be used for the FancyMessages but for some player handling stuff soon.

2. This isn't even a commit worth pulling for me. It doesn't have any changes on the plugin nor does it have any uses.

Closed

**Comment by ZVL2SOQEE4** [comment]
sorry, i thought this was a legitimate plugin. i just realized now that this is a mirror of @gnat008's per world inventory. i can help in case you want to learn how forks work.

**Comment by Jaryn-R** [comment]
Yeah whatever kid saying you just signed up you probably have zero programming experience. And that's most likely why you only changed package files and the pom.xml. Have a nice day

**Comment by ljacqu** [comment]
you realize this pr was a subtle hint at the fact that project scorpion is copied code with some minor redundant additions by you? and now we realize that this also applies to this repository. embarrassing if you ask me.

so i wouldn't be talking about lack of skill. if i take a quick look in your git history i see comedy stuff like d3fb02f, 8b5a772, and 835f474 (were the unit tests beyond your understanding? top kek)

anyway enough time wasted on this, byr bye

**Pull request closed without merging**
